services:
  app:
    # image: ghcr.io/pythoninthegrass/docker_graphical:dev
    container_name: docker-graphical
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    init: true
    shm_size: 2g
    # GPU PASSTHROUGH
    deploy:
      resources:
        reservations:
          # Enable support for NVIDIA GPUs.
          # Ref: https://docs.docker.com/compose/gpu-support/#enabling-gpu-access-to-service-containers
          devices:
            - capabilities: [gpu]
              device_ids: ["${NVIDIA_VISIBLE_DEVICES}"]
    hostname: ${NAME:-localhost}
    extra_hosts:
      - "${NAME:-localhost}:127.0.0.1"
    environment:
      - TZ=${TZ:-Etc/UTC}
      - ENABLE_STEAM=${ENABLE_STEAM:-true}
      - STEAM_ARGS=${STEAM_ARGS:-"-silent"}
      - ENABLE_SUNSHINE=${ENABLE_SUNSHINE:-true}
    devices:
      - /dev/fuse
      - /dev/uinput
    device_cgroup_rules:
      - 'c 13:* rmw'
    # TODO: fails to connect to xrdp if volumes are mounted
    volumes:
      - ./data/games:/mnt/games:rw
      # - ./data/ssh:/etc/dropbear
      # - ./data/xrdp:/etc/xrdp

networks:
  default:
    driver: bridge
